name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: instalar dependencias do backend
        run: npm install
        working-directory: backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: instalar dependencias do frontend
        run: npm install
        working-directory: frontend

      - name: build do frontend
        run: npm run build
        working-directory: frontend
        env:
          CI: false
